### ISSUE TITLE
How you used WebCrypto API

### ISSUE THREAD

**Issue by subversivo58** [trentmwillis/trentmwillis.github.io#17]
I was curious following his [January 1º post](https://pretty-okay.dev/2019/01/01/creating-your-own-image-format).

I thought interesting case and tried to reproduce but I ran into the question how exactly did you encrypt it and saved a file using `WebCrypto`?

I tried to encrypt photos with `FileReader()` API by getting an `ArrayBuffer` from the `<input>` element, tried with `fetch()` but could not see them in the document.

Could you describe the steps you took to encrypt and save?

**Comment by trentmwillis** [comment]
Hi @subversivo58, I probably won't have the time to do a write-up on that portion, but I do still have a demo of it. I'll clean it up and post it online soon (probably tomorrow).

**Comment by trentmwillis** [comment]
Here ya go: https://glitch.com/~encrypt-image. Hope this helps fill in the gaps!

**Comment by subversivo58** [comment]
@trentmwillis thank you

I could understand the steps now
